spring:
  cloud:
    nacos:
      discovery:
        metadata:
          context-path: ${spring.application.name}
        server-addr: app.luopc.com:8848,data.luopc.com:8848,core.luopc.com:8848
        username: nacos

        #context-path: ${server.servlet.context-path}

---
spring:
  config:
    activate:
      on-profile: local
  # 服务发现
  cloud:
    nacos:
      password: ENC(hCnv7xrkjPYoxZXbLZ8QAk0lsjt6SQL6)
      discovery:
        group: local
        namespace: local
      config:
        group: local
        namespace: local

---
spring:
  config:
    activate:
      on-profile: dev
  # 服务发现
  cloud:
    nacos:
      password: ENC(YmWU8yNK1OWrqnfeQq0nVOMBba37YfEL)
      discovery:
        group: dev
        namespace: dev
      config:
        group: dev
        namespace: dev

---
spring:
  config:
    activate:
      on-profile: uat
  # 服务发现
  cloud:
    nacos:
      password: ENC(hbJgW4YivoXPjo4NbZWGMV+G+B+3Oi5N)
      discovery:
        group: uat
        namespace: uat
      config:
        group: uat
        namespace: uat

