spring:
  data:
    mongodb:
      host: data.luopc.com
      port: 27017
      database: admin
      username: admin
      password: ENC(XBbkk5H8Z/2ANkIT3XoI52j9dwZcaEEN)
      authentication-database: drs
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      database: admin
      username: test_user
      password: ENC(jvCX2Zho1QQxzX8UT8qUQf6t9DZRN0oL)

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: uat
