spring:
  rabbitmq:
    host: data.luopc.com
    port: 5672
    publisher-returns: true

---
spring:
  config:
    activate:
      on-profile: dev
  # rabbitmq
  rabbitmq:
    username: dev
    password: ENC(4/DJz6Mkcn4kZIU4a/kUA322GCy1gqlB)
    virtualHost: dev

---
spring:
  config:
    activate:
      on-profile: uat
  # rabbitmq
  rabbitmq:
    username: uat
    password: ENC(9WmnsYixW2/E7iWFnyETYxzM3VK/tqqd)
    virtualHost: uat
