spring:
  rabbitmq:
    host: data.luopc.com
    port: 5672
    publisher-returns: true

---
spring:
  config:
    activate:
      on-profile: dev
  # rabbitmq
  rabbitmq:
    username: dev
    password: Robin2023
    virtualHost: dev

---
spring:
  config:
    activate:
      on-profile: uat
  # rabbitmq
  rabbitmq:
    username: uat
    password: Robin2023
    virtualHost: uat
